### PR TITLE
logback logstash json encoder using avaje-jsonb

### PR DESCRIPTION
**Pull request by rbygrave**

### CODE REVIEW

**Review by SentryMan — APPROVED** [review]
now this I like

**Comment by SentryMan** [comment]
should we split it into its own repo though?

**Comment by SentryMan** [comment]
also does it support MDC

**Comment by SentryMan** [comment]
on my local, I added this and it works for MDC 
```java
      event
          .getMDCPropertyMap()
          .forEach(
              (k, v) -> {
                writer.name(k);
                writer.value(v);
              });
```

**Comment by rbygrave** [comment]
Yeah, I'm also thinking that it probably should have its own repo. 

Nice on the mdc too!!

**Pull request closed without merging**
